<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style></style>
  </head>
  <body>
    <script>
      async function fn() {
        //1.若返回的结果不是promise的对象，则返回结果一定是一个成功的promise,值为返回的值
        // return "aaa";
        // 2. 抛出错误,返回的是一个失败的promise，值为返回的对象。
        // throw new Error("出错了");
        //3.返回的是promise对象
        return new Promise((reslove, reject) => {
          // reslove("成功的数据");
          reject("失败的错误");
        });
      }
      const result = fn();
      result
        .then((res) => {
          console.log(res);
        })
        .catch((err) => {
          console.warn(err);
        });
      console.log(result);
    </script>
  </body>
</html>
